# EN
METAL_MINE = 1
CRYSTAL_MINE = 2
DEUTERIUM_SYNTHESIZER = 3
SOLAR_PLANT = 4
FUSION_REACTOR = 12
METAL_STORAGE = 22
CRYSTAL_STORAGE = 23
DEUTERIUM_TANK = 24
SCHIELDED_METAL_DEN = 25
UNDERGROUD_CRYSTAL_DEN = 26
SEABED_DEUTERIUM_DEN = 27

# NL
METAALMIJN = 1
KRISTALMIJN = 2
DEUTERIUMFABRIEK = 3
ZONNE_ENERGIECENTRALE = 4
FUSIECENTRALE = 12
METAALOPSLAG = 22
KRISTALOPSLAG = 23
DEUTERIUMTANK = 24
