techtree = {(1, 1, 'supplies'): {},
            (2, 1, 'supplies'): {},
            (3, 1, 'supplies'): {},
            (4, 1, 'supplies'): {},
            (12, 1, 'supplies'): {(3, 1, 'supplies'): 5,
                                  (31, 1, 'facilities'): 1,
                                  (113, 1, 'research'): 3},
            (14, 1, 'facilities'): {},
            (15, 1, 'facilities'): {(14, 1, 'facilities'): 10,
                                    (31, 1, 'facilities'): 1,
                                    (108, 1, 'research'): 10},
            (21, 1, 'facilities'): {(14, 1, 'facilities'): 2},
            (22, 1, 'supplies'): {},
            (23, 1, 'supplies'): {},
            (24, 1, 'supplies'): {},
            (31, 1, 'facilities'): {},
            (33, 1, 'facilities'): {(14, 1, 'facilities'): 10,
                                    (15, 1, 'facilities'): 1,
                                    (31, 1, 'facilities'): 1,
                                    (108, 1, 'research'): 10,
                                    (113, 1, 'research'): 12},
            (34, 1, 'facilities'): {},
            (36, 1, 'facilities'): {(14, 1, 'facilities'): 2, (21, 1, 'facilities'): 2},
            (44, 1, 'facilities'): {(14, 1, 'facilities'): 2, (21, 1, 'facilities'): 1},
            (106, 1, 'research'): {(31, 1, 'facilities'): 3},
            (108, 1, 'research'): {(31, 1, 'facilities'): 1},
            (109, 1, 'research'): {(31, 1, 'facilities'): 4},
            (110, 1, 'research'): {(31, 1, 'facilities'): 6, (113, 1, 'research'): 3},
            (111, 1, 'research'): {(31, 1, 'facilities'): 2},
            (113, 1, 'research'): {(31, 1, 'facilities'): 1},
            (114, 1, 'research'): {(31, 1, 'facilities'): 7,
                                   (110, 1, 'research'): 5,
                                   (113, 1, 'research'): 5},
            (115, 1, 'research'): {(31, 1, 'facilities'): 1, (113, 1, 'research'): 1},
            (117, 1, 'research'): {(31, 1, 'facilities'): 2, (113, 1, 'research'): 1},
            (118, 1, 'research'): {(31, 1, 'facilities'): 7,
                                   (110, 1, 'research'): 5,
                                   (113, 1, 'research'): 5,
                                   (114, 1, 'research'): 3},
            (120, 1, 'research'): {(31, 1, 'facilities'): 1, (113, 1, 'research'): 2},
            (121, 1, 'research'): {(31, 1, 'facilities'): 4,
                                   (113, 1, 'research'): 4,
                                   (120, 1, 'research'): 5},
            (122, 1, 'research'): {(31, 1, 'facilities'): 4,
                                   (113, 1, 'research'): 8,
                                   (120, 1, 'research'): 10,
                                   (121, 1, 'research'): 5},
            (123, 1, 'research'): {(31, 1, 'facilities'): 10,
                                   (108, 1, 'research'): 8,
                                   (110, 1, 'research'): 5,
                                   (113, 1, 'research'): 5,
                                   (114, 1, 'research'): 8},
            (124, 1, 'research'): {(31, 1, 'facilities'): 3,
                                   (106, 1, 'research'): 4,
                                   (113, 1, 'research'): 1,
                                   (117, 1, 'research'): 3},
            (199, 1, 'research'): {(31, 1, 'facilities'): 12},
            (202, 1, 'shipyard'): {(14, 1, 'facilities'): 2,
                                   (21, 1, 'facilities'): 2,
                                   (31, 1, 'facilities'): 1,
                                   (113, 1, 'research'): 1,
                                   (115, 1, 'research'): 2},
            (203, 1, 'shipyard'): {(14, 1, 'facilities'): 2,
                                   (21, 1, 'facilities'): 4,
                                   (31, 1, 'facilities'): 1,
                                   (113, 1, 'research'): 1,
                                   (115, 1, 'research'): 6},
            (204, 1, 'shipyard'): {(14, 1, 'facilities'): 2,
                                   (21, 1, 'facilities'): 1,
                                   (31, 1, 'facilities'): 1,
                                   (113, 1, 'research'): 1,
                                   (115, 1, 'research'): 1},
            (205, 1, 'shipyard'): {(14, 1, 'facilities'): 2,
                                   (21, 1, 'facilities'): 3,
                                   (31, 1, 'facilities'): 2,
                                   (111, 1, 'research'): 2,
                                   (113, 1, 'research'): 1,
                                   (117, 1, 'research'): 2},
            (206, 1, 'shipyard'): {(14, 1, 'facilities'): 2,
                                   (21, 1, 'facilities'): 5,
                                   (31, 1, 'facilities'): 4,
                                   (113, 1, 'research'): 4,
                                   (117, 1, 'research'): 4,
                                   (120, 1, 'research'): 5,
                                   (121, 1, 'research'): 2},
            (207, 1, 'shipyard'): {(14, 1, 'facilities'): 2,
                                   (21, 1, 'facilities'): 7,
                                   (31, 1, 'facilities'): 7,
                                   (110, 1, 'research'): 5,
                                   (113, 1, 'research'): 5,
                                   (114, 1, 'research'): 3,
                                   (118, 1, 'research'): 4},
            (208, 1, 'shipyard'): {(14, 1, 'facilities'): 2,
                                   (21, 1, 'facilities'): 4,
                                   (31, 1, 'facilities'): 2,
                                   (113, 1, 'research'): 1,
                                   (117, 1, 'research'): 3},
            (209, 1, 'shipyard'): {(14, 1, 'facilities'): 2,
                                   (21, 1, 'facilities'): 4,
                                   (31, 1, 'facilities'): 6,
                                   (110, 1, 'research'): 2,
                                   (113, 1, 'research'): 3,
                                   (115, 1, 'research'): 6},
            (210, 1, 'shipyard'): {(14, 1, 'facilities'): 2,
                                   (21, 1, 'facilities'): 3,
                                   (31, 1, 'facilities'): 3,
                                   (106, 1, 'research'): 2,
                                   (113, 1, 'research'): 1,
                                   (115, 1, 'research'): 3},
            (211, 1, 'shipyard'): {(14, 1, 'facilities'): 2,
                                   (21, 1, 'facilities'): 8,
                                   (31, 1, 'facilities'): 4,
                                   (113, 1, 'research'): 8,
                                   (117, 1, 'research'): 6,
                                   (120, 1, 'research'): 10,
                                   (121, 1, 'research'): 5,
                                   (122, 1, 'research'): 5},
            (212, 1, 'supplies'): {(14, 1, 'facilities'): 2, (21, 1, 'facilities'): 1},
            (213, 1, 'shipyard'): {(14, 1, 'facilities'): 2,
                                   (21, 1, 'facilities'): 9,
                                   (31, 1, 'facilities'): 7,
                                   (110, 1, 'research'): 5,
                                   (113, 1, 'research'): 5,
                                   (114, 1, 'research'): 5,
                                   (118, 1, 'research'): 6},
            (214, 1, 'shipyard'): {(14, 1, 'facilities'): 2,
                                   (21, 1, 'facilities'): 12,
                                   (31, 1, 'facilities'): 12,
                                   (110, 1, 'research'): 5,
                                   (113, 1, 'research'): 5,
                                   (114, 1, 'research'): 6,
                                   (118, 1, 'research'): 7,
                                   (199, 1, 'research'): 1},
            (215, 1, 'shipyard'): {(14, 1, 'facilities'): 2,
                                   (21, 1, 'facilities'): 8,
                                   (31, 1, 'facilities'): 7,
                                   (110, 1, 'research'): 5,
                                   (113, 1, 'research'): 5,
                                   (114, 1, 'research'): 5,
                                   (118, 1, 'research'): 5,
                                   (120, 1, 'research'): 12},
            (217, 1, 'supplies'): {(14, 1, 'facilities'): 2,
                                   (21, 1, 'facilities'): 5,
                                   (31, 1, 'facilities'): 2,
                                   (111, 1, 'research'): 4,
                                   (113, 1, 'research'): 2,
                                   (115, 1, 'research'): 4,
                                   (120, 1, 'research'): 4},
            (218, 1, 'shipyard'): {(14, 1, 'facilities'): 2,
                                   (21, 1, 'facilities'): 10,
                                   (31, 1, 'facilities'): 7,
                                   (110, 1, 'research'): 6,
                                   (113, 1, 'research'): 5,
                                   (114, 1, 'research'): 6,
                                   (118, 1, 'research'): 7},
            (219, 1, 'shipyard'): {(14, 1, 'facilities'): 2,
                                   (21, 1, 'facilities'): 5,
                                   (31, 1, 'facilities'): 7,
                                   (110, 1, 'research'): 5,
                                   (113, 1, 'research'): 5,
                                   (114, 1, 'research'): 3,
                                   (118, 1, 'research'): 2},
            (401, 1, 'defenses'): {(14, 1, 'facilities'): 2, (21, 1, 'facilities'): 1},
            (402, 1, 'defenses'): {(14, 1, 'facilities'): 2,
                                   (21, 1, 'facilities'): 2,
                                   (31, 1, 'facilities'): 1,
                                   (113, 1, 'research'): 2,
                                   (120, 1, 'research'): 3},
            (403, 1, 'defenses'): {(14, 1, 'facilities'): 2,
                                   (21, 1, 'facilities'): 4,
                                   (31, 1, 'facilities'): 1,
                                   (113, 1, 'research'): 3,
                                   (120, 1, 'research'): 6},
            (404, 1, 'defenses'): {(14, 1, 'facilities'): 2,
                                   (21, 1, 'facilities'): 6,
                                   (31, 1, 'facilities'): 6,
                                   (109, 1, 'research'): 3,
                                   (110, 1, 'research'): 1,
                                   (113, 1, 'research'): 6},
            (405, 1, 'defenses'): {(14, 1, 'facilities'): 2,
                                   (21, 1, 'facilities'): 4,
                                   (31, 1, 'facilities'): 4,
                                   (113, 1, 'research'): 4,
                                   (120, 1, 'research'): 5,
                                   (121, 1, 'research'): 4},
            (406, 1, 'defenses'): {(14, 1, 'facilities'): 2,
                                   (21, 1, 'facilities'): 8,
                                   (31, 1, 'facilities'): 4,
                                   (113, 1, 'research'): 8,
                                   (120, 1, 'research'): 10,
                                   (121, 1, 'research'): 5,
                                   (122, 1, 'research'): 7},
            (407, 1, 'defenses'): {(14, 1, 'facilities'): 2,
                                   (21, 1, 'facilities'): 1,
                                   (31, 1, 'facilities'): 6,
                                   (110, 1, 'research'): 2,
                                   (113, 1, 'research'): 3},
            (408, 1, 'defenses'): {(14, 1, 'facilities'): 2,
                                   (21, 1, 'facilities'): 6,
                                   (31, 1, 'facilities'): 6,
                                   (110, 1, 'research'): 6,
                                   (113, 1, 'research'): 3},
            (502, 1, 'defenses'): {(14, 1, 'facilities'): 2,
                                   (21, 1, 'facilities'): 1,
                                   (44, 1, 'facilities'): 2},
            (503, 1, 'defenses'): {(14, 1, 'facilities'): 2,
                                   (21, 1, 'facilities'): 1,
                                   (31, 1, 'facilities'): 2,
                                   (44, 1, 'facilities'): 4,
                                   (113, 1, 'research'): 1,
                                   (117, 1, 'research'): 1}}


def get(id):
    return techtree[id]
